# https://travis-ci.org/dashboard
# https://config.travis-ci.com/explore

os: linux
dist: bionic
language: minimal
addons:
   apt:
      packages:
         - gfortran-8
arch:
  - amd64
branches:
  only:
  - master
script:
  - cd util/developers
  - python run_all_testcases.py --show_logs harness --compiler gfortran-8
