# https://travis-ci.org/dashboard
# https://config.travis-ci.com/explore

os: linux
dist: bionic
language: minimal
arch:
  - amd64
branches:
  only:
    - master
job:
  include:
    - addons:
        apt:
          packages: gfortran-5
      script: python util/developers/run_all_testcases.py --show_logs harness --compiler gfortran-5
    - addons:
        apt:
          packages: gfortran-7
      script: python util/developers/run_all_testcases.py --show_logs harness --compiler gfortran-7
    - addons:
        apt:
          packages: gfortran-8
      script: python util/developers/run_all_testcases.py --show_logs harness --compiler gfortran-8 -DFABM_USE_CONTIGUOUS=OFF
