# https://travis-ci.org/dashboard
# https://config.travis-ci.com/explore

os: linux
dist: bionic
language: minimal
arch:
  - amd64
branches:
  only:
    - master
job:
  include:
    - addons:
        apt:
          packages: gfortran-5 python-numpy
      script:
        - python util/developers/run_all_testcases.py harness --show_logs --compiler gfortran-5
        - python util/developers/run_all_testcases.py pyfabm --show_logs --compiler gfortran-5
    - addons:
        apt:
          packages: gfortran-6 python-numpy
      script:
        - python util/developers/run_all_testcases.py harness --show_logs --compiler gfortran-6
        - python util/developers/run_all_testcases.py pyfabm --show_logs --compiler gfortran-6
    - addons:
        apt:
          packages: gfortran-7 python-numpy
      script:
        - python util/developers/run_all_testcases.py harness --show_logs --compiler gfortran-7
        - python util/developers/run_all_testcases.py pyfabm --show_logs --compiler gfortran-7
    - addons:
        apt:
          packages: gfortran-8 python-numpy
      script:
        - python util/developers/run_all_testcases.py harness --show_logs --compiler gfortran-8 -DFABM_USE_CONTIGUOUS=OFF
        - python util/developers/run_all_testcases.py pyfabm --show_logs --compiler gfortran-8 -DFABM_USE_CONTIGUOUS=OFF
    - addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: gfortran-9 python-numpy
      script:
        - python util/developers/run_all_testcases.py harness --show_logs --compiler gfortran-9
        - python util/developers/run_all_testcases.py pyfabm --show_logs --compiler gfortran-9
    - addons:
        apt:
          packages: python-numpy
      env:
        - NVHPC_SILENT=true
        - NVHPC_INSTALL_DIR=${HOME}/nvhpc
        - NVHPC_INSTALL_TYPE=single
      before_install:
        - wget https://developer.download.nvidia.com/hpc-sdk/20.9/nvhpc_2020_209_Linux_x86_64_cuda_11.0.tar.gz
        - tar xpzf nvhpc_2020_209_Linux_x86_64_cuda_11.0.tar.gz
        - nvhpc_2020_209_Linux_x86_64_cuda_11.0/install
      script:
        - python util/developers/run_all_testcases.py harness --show_logs --compiler ${HOME}/nvhpc/Linux_x86_64/20.9/compilers/bin/pgfortran
        - python util/developers/run_all_testcases.py pyfabm --show_logs --compiler ${HOME}/nvhpc/Linux_x86_64/20.9/compilers/bin/pgfortran
    - addons:
        apt:
          packages: python-numpy
      before_install:
        - wget https://registrationcenter-download.intel.com/akdlm/irc_nas/17508/l_fortran-compiler_p_2021.1.2.62_offline.sh
        - /usr/sh l_fortran-compiler_p_2021.1.2.62_offline.sh -a --silent --cli --install-dir ${HOME}/intel --eula accept
        - ${HOME}/intel/setvars.sh
      script:
        - python util/developers/run_all_testcases.py harness --show_logs --compiler ifort
        - python util/developers/run_all_testcases.py pyfabm --show_logs --compiler ifort
